# Generated by Django 4.1.2 on 2022-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publish_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
